# VacationPy
---

## Starter Code to Import Libraries and Load the Weather and Coordinates Data

In [1]:
# Dependencies and Setup
import hvplot.pandas
import pandas as pd
import requests
import cartopy
import geoviews
import pyproj

# Import API key
from api_keys import geoapify_key

In [2]:
# Load the CSV file created in Part 1 into a Pandas DataFrame
city_data_df = pd.read_csv("output_data/cities.csv")

# Display sample data
city_data_df.head()

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,adamstown,-25.0660,-130.1015,21.29,87,100,7.03,PN,1728613084
1,1,ilulissat,69.2167,-51.1000,-1.99,43,46,1.03,GL,1728613084
2,2,lepsy,46.2350,78.9456,17.30,35,100,2.88,KZ,1728613085
3,3,bethel,41.3712,-73.4140,9.05,69,0,3.09,US,1728613085
4,4,black forest,39.0131,-104.7008,16.55,29,0,3.60,US,1728613085

---

### Step 1: Create a map that displays a point for every city in the `city_data_df` DataFrame. The size of the point should be the humidity in each city.

In [3]:
# Create the map plot
map_plot = city_data_df.hvplot.points(
    'Lng',
    'Lat',
    geo=True,
    tiles='EsriImagery',
    size='Humidity',
    color='City',
    frame_width=800,
    frame_height=600
)

# Display the map
map_plot

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Lng,Lat]   (City,Humidity)

### Step 2: Narrow down the `city_data_df` DataFrame to find your ideal weather condition

In [4]:
# Narrow down cities that fit criteria and drop any results with null values
min_temp_s = city_data_df["Max Temp"] > 21
max_temp_s = city_data_df["Max Temp"] < 27
wind_speed_s = city_data_df["Wind Speed"] > 5

city_temp_range_df = city_data_df[min_temp_s & max_temp_s & wind_speed_s]
city_temp_range_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,adamstown,-25.0660,-130.1015,21.29,87,100,7.03,PN,1728613084
7,7,mont-dore,-22.2833,166.5833,24.07,62,0,5.80,NC,1728613086
10,10,port mathurin,-19.6833,63.4167,22.31,79,100,10.56,MU,1728613086
60,60,uturoa,-16.7333,-151.4333,23.88,85,100,9.13,PF,1728613099
69,69,west island,-12.1568,96.8225,26.99,78,20,7.72,CC,1728613101
99,99,bandarbeyla,9.4942,50.8122,25.16,91,64,7.22,SO,1728613109
117,117,afaahiti,-17.7500,-149.2833,21.69,90,100,9.62,PF,1728613113
145,145,piacabucu,-10.4056,-36.4344,25.43,69,100,5.38,BR,1728613120
150,150,ta`u,-14.2336,-169.5144,26.72,81,51,8.61,AS,1728613121
154,154,nova sintra,14.8667,-24.7167,26.64,85,100,9.93,CV,1728613121
157,157,pitimbu,-7.4706,-34.8086,25.02,74,100,5.33,BR,1728613122
186,186,avarua,-21.2078,-159.7750,25.03,73,40,7.72,CK,1728613129
206,206,tolanaro,-25.0319,46.9987,21.04,78,20,9.26,MG,1728613134
210,210,forster,-32.1667,152.5167,23.54,69,3,5.06,AU,1728613135
224,224,mahina,-17.5065,-149.4890,24.87,78,75,8.23,PF,1728613138
265,265,port augusta,-32.5000,137.7667,21.20,26,100,6.68,AU,1728613148
278,278,souillac,-20.5167,57.5167,22.21,73,40,6.17,MU,1728613151
307,307,yeppoon,-23.1333,150.7333,23.14,72,6,8.80,AU,1728613158
331,331,shenjiamen,29.9576,122.2980,22.23,63,54,5.47,CN,1728613164
334,334,tataouine,32.9297,10.4518,23.11,88,10,5.35,TN,1728613164
354,354,sola,-13.8833,167.5500,26.49,80,100,6.77,VU,1728613169
359,359,nuku'alofa,-21.1333,-175.2000,26.19,89,75,6.17,TO,1728613170
409,409,yeed,4.5500,43.0333,23.14,67,22,7.24,SO,1728613181
426,426,tangalle,6.0240,80.7911,25.47,89,100,7.81,LK,1728613185
443,443,dhidhdhoo,6.8833,73.1000,26.15,88,100,9.76,MV,1728613189
470,470,trairi,-3.2778,-39.2689,25.70,74,52,5.71,BR,1728613195
505,505,sao joao da barra,-21.6403,-41.0511,22.36,91,100,7.61,BR,1728613203
506,506,lamu,-2.2717,40.9020,24.70,84,22,6.59,KE,1728613203
510,510,cabrobo,-8.5142,-39.3100,25.71,60,20,10.14,BR,1728613204
576,576,kavaratti,10.5669,72.6420,26.39,86,98,7.10,IN,1728613220
585,585,armacao de buzios,-22.7469,-41.8817,21.20,92,100,9.62,BR,1728613223
587,587,ulladulla,-35.3500,150.4667,21.18,57,35,6.04,AU,1728613177

In [5]:
# Drop any rows with null values
clean_city_temp_range_df = city_temp_range_df.dropna()

# Display sample data
clean_city_temp_range_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,adamstown,-25.0660,-130.1015,21.29,87,100,7.03,PN,1728613084
7,7,mont-dore,-22.2833,166.5833,24.07,62,0,5.80,NC,1728613086
10,10,port mathurin,-19.6833,63.4167,22.31,79,100,10.56,MU,1728613086
60,60,uturoa,-16.7333,-151.4333,23.88,85,100,9.13,PF,1728613099
69,69,west island,-12.1568,96.8225,26.99,78,20,7.72,CC,1728613101
99,99,bandarbeyla,9.4942,50.8122,25.16,91,64,7.22,SO,1728613109
117,117,afaahiti,-17.7500,-149.2833,21.69,90,100,9.62,PF,1728613113
145,145,piacabucu,-10.4056,-36.4344,25.43,69,100,5.38,BR,1728613120
150,150,ta`u,-14.2336,-169.5144,26.72,81,51,8.61,AS,1728613121
154,154,nova sintra,14.8667,-24.7167,26.64,85,100,9.93,CV,1728613121
157,157,pitimbu,-7.4706,-34.8086,25.02,74,100,5.33,BR,1728613122
186,186,avarua,-21.2078,-159.7750,25.03,73,40,7.72,CK,1728613129
206,206,tolanaro,-25.0319,46.9987,21.04,78,20,9.26,MG,1728613134
210,210,forster,-32.1667,152.5167,23.54,69,3,5.06,AU,1728613135
224,224,mahina,-17.5065,-149.4890,24.87,78,75,8.23,PF,1728613138
265,265,port augusta,-32.5000,137.7667,21.20,26,100,6.68,AU,1728613148
278,278,souillac,-20.5167,57.5167,22.21,73,40,6.17,MU,1728613151
307,307,yeppoon,-23.1333,150.7333,23.14,72,6,8.80,AU,1728613158
331,331,shenjiamen,29.9576,122.2980,22.23,63,54,5.47,CN,1728613164
334,334,tataouine,32.9297,10.4518,23.11,88,10,5.35,TN,1728613164
354,354,sola,-13.8833,167.5500,26.49,80,100,6.77,VU,1728613169
359,359,nuku'alofa,-21.1333,-175.2000,26.19,89,75,6.17,TO,1728613170
409,409,yeed,4.5500,43.0333,23.14,67,22,7.24,SO,1728613181
426,426,tangalle,6.0240,80.7911,25.47,89,100,7.81,LK,1728613185
443,443,dhidhdhoo,6.8833,73.1000,26.15,88,100,9.76,MV,1728613189
470,470,trairi,-3.2778,-39.2689,25.70,74,52,5.71,BR,1728613195
505,505,sao joao da barra,-21.6403,-41.0511,22.36,91,100,7.61,BR,1728613203
506,506,lamu,-2.2717,40.9020,24.70,84,22,6.59,KE,1728613203
510,510,cabrobo,-8.5142,-39.3100,25.71,60,20,10.14,BR,1728613204
576,576,kavaratti,10.5669,72.6420,26.39,86,98,7.10,IN,1728613220
585,585,armacao de buzios,-22.7469,-41.8817,21.20,92,100,9.62,BR,1728613223
587,587,ulladulla,-35.3500,150.4667,21.18,57,35,6.04,AU,1728613177

### Step 3: Create a new DataFrame called `hotel_df`.

In [6]:
# Use the Pandas copy function to create DataFrame called hotel_df to store the city, country, coordinates, and humidity
hotel_df = clean_city_temp_range_df.copy()

# Add an empty column, "Hotel Name," to the DataFrame so you can store the hotel found using the Geoapify API
hotel_df["Hotel Name"] = ""

# Display sample data
hotel_df

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,0,adamstown,-25.0660,-130.1015,21.29,87,100,7.03,PN,1728613084,
7,7,mont-dore,-22.2833,166.5833,24.07,62,0,5.80,NC,1728613086,
10,10,port mathurin,-19.6833,63.4167,22.31,79,100,10.56,MU,1728613086,
60,60,uturoa,-16.7333,-151.4333,23.88,85,100,9.13,PF,1728613099,
69,69,west island,-12.1568,96.8225,26.99,78,20,7.72,CC,1728613101,
99,99,bandarbeyla,9.4942,50.8122,25.16,91,64,7.22,SO,1728613109,
117,117,afaahiti,-17.7500,-149.2833,21.69,90,100,9.62,PF,1728613113,
145,145,piacabucu,-10.4056,-36.4344,25.43,69,100,5.38,BR,1728613120,
150,150,ta`u,-14.2336,-169.5144,26.72,81,51,8.61,AS,1728613121,
154,154,nova sintra,14.8667,-24.7167,26.64,85,100,9.93,CV,1728613121,
157,157,pitimbu,-7.4706,-34.8086,25.02,74,100,5.33,BR,1728613122,
186,186,avarua,-21.2078,-159.7750,25.03,73,40,7.72,CK,1728613129,
206,206,tolanaro,-25.0319,46.9987,21.04,78,20,9.26,MG,1728613134,
210,210,forster,-32.1667,152.5167,23.54,69,3,5.06,AU,1728613135,
224,224,mahina,-17.5065,-149.4890,24.87,78,75,8.23,PF,1728613138,
265,265,port augusta,-32.5000,137.7667,21.20,26,100,6.68,AU,1728613148,
278,278,souillac,-20.5167,57.5167,22.21,73,40,6.17,MU,1728613151,
307,307,yeppoon,-23.1333,150.7333,23.14,72,6,8.80,AU,1728613158,
331,331,shenjiamen,29.9576,122.2980,22.23,63,54,5.47,CN,1728613164,
334,334,tataouine,32.9297,10.4518,23.11,88,10,5.35,TN,1728613164,
354,354,sola,-13.8833,167.5500,26.49,80,100,6.77,VU,1728613169,
359,359,nuku'alofa,-21.1333,-175.2000,26.19,89,75,6.17,TO,1728613170,
409,409,yeed,4.5500,43.0333,23.14,67,22,7.24,SO,1728613181,
426,426,tangalle,6.0240,80.7911,25.47,89,100,7.81,LK,1728613185,
443,443,dhidhdhoo,6.8833,73.1000,26.15,88,100,9.76,MV,1728613189,
470,470,trairi,-3.2778,-39.2689,25.70,74,52,5.71,BR,1728613195,
505,505,sao joao da barra,-21.6403,-41.0511,22.36,91,100,7.61,BR,1728613203,
506,506,lamu,-2.2717,40.9020,24.70,84,22,6.59,KE,1728613203,
510,510,cabrobo,-8.5142,-39.3100,25.71,60,20,10.14,BR,1728613204,
576,576,kavaratti,10.5669,72.6420,26.39,86,98,7.10,IN,1728613220,
585,585,armacao de buzios,-22.7469,-41.8817,21.20,92,100,9.62,BR,1728613223,
587,587,ulladulla,-35.3500,150.4667,21.18,57,35,6.04,AU,1728613177,

### Step 4: For each city, use the Geoapify API to find the first hotel located within 10,000 metres of your coordinates.

In [7]:
# Set parameters to search for a hotel
radius = 10000
limit = 1
categories = "accommodation.hotel"

#create a params dictionary
params = {
    "categories":categories,
    "limit":limit,
    "apiKey":geoapify_key     
}

# Print a message to follow up the hotel search
print("Starting hotel search")

# Iterate through the hotel_df DataFrame
for index, row in hotel_df.iterrows():
    # get latitude, longitude from the DataFrame
    lng = hotel_df.loc[index, "Lng"]
    lat = hotel_df.loc[index, "Lat"]
    # Add filter and bias parameters with the current city's latitude and longitude to the params dictionary
    params["filter"] = f"circle:{lng},{lat},{radius}"
    params["bias"] = f"proximity:{lng},{lat}"
    
    # Set base URL
    base_url = "https://api.geoapify.com/v2/places"


    # Make and API request using the params dictionaty
    name_address = requests.get(base_url, params = params)
    print(name_address.url)
    # Convert the API response to JSON format
    name_address =  name_address = name_address.json()
    
    # Grab the first hotel from the results and store the name in the hotel_df DataFrame
    try:
        hotel_df.loc[index, "Hotel Name"] = name_address["features"][0]["properties"]["name"]
    except (KeyError, IndexError):
        # If no hotel is found, set the hotel name as "No hotel found".
        hotel_df.loc[index, "Hotel Name"] = "No hotel found"
        
    # Log the search results
    print(f"{hotel_df.loc[index, 'City']} - nearest hotel: {hotel_df.loc[index, 'Hotel Name']}")

# Display sample data
hotel_df

Starting hotel search
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-130.1015%2C-25.066%2C10000&bias=proximity%3A-130.1015%2C-25.066
adamstown - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A166.5833%2C-22.2833%2C10000&bias=proximity%3A166.5833%2C-22.2833
mont-dore - nearest hotel: Les Cases de Plum
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A63.4167%2C-19.6833%2C10000&bias=proximity%3A63.4167%2C-19.6833
port mathurin - nearest hotel: Escale Vacances
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-151.4333%2C-16.7333%2C10000&bias=proximity%3A-151.4333%2C-16.7333
uturoa - nearest hotel: Hawaiki Nui hotel
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A96.8225%2C-12.1568%2C10000&bias=proximity%3A96.8225%2C-12.1568
west island - nearest hotel: Cocos Village Bungalows
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A50.8122%2C9.4942%2C10000&bias=proximity%3A50.8122%2C9.4942
bandarbeyla - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-149.2833%2C-17.75%2C10000&bias=proximity%3A-149.2833%2C-17.75
afaahiti - nearest hotel: Omati Lodge
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-36.4344%2C-10.4056%2C10000&bias=proximity%3A-36.4344%2C-10.4056
piacabucu - nearest hotel: O Leão
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-169.5144%2C-14.2336%2C10000&bias=proximity%3A-169.5144%2C-14.2336
ta`u - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-24.7167%2C14.8667%2C10000&bias=proximity%3A-24.7167%2C14.8667
nova sintra - nearest hotel: Residência Ka Dencho
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-34.8086%2C-7.4706%2C10000&bias=proximity%3A-34.8086%2C-7.4706
pitimbu - nearest hotel: Pousada Brisa Mar
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-159.775%2C-21.2078%2C10000&bias=proximity%3A-159.775%2C-21.2078
avarua - nearest hotel: Paradise Inn
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A46.9987%2C-25.0319%2C10000&bias=proximity%3A46.9987%2C-25.0319
tolanaro - nearest hotel: Hôtel Mahavokey
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A152.5167%2C-32.1667%2C10000&bias=proximity%3A152.5167%2C-32.1667
forster - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-149.489%2C-17.5065%2C10000&bias=proximity%3A-149.489%2C-17.5065
mahina - nearest hotel: Motu Martin
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A137.7667%2C-32.5%2C10000&bias=proximity%3A137.7667%2C-32.5
port augusta - nearest hotel: Hotel Commonwealth
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A57.5167%2C-20.5167%2C10000&bias=proximity%3A57.5167%2C-20.5167
souillac - nearest hotel: Hotel SkylineInn
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A150.7333%2C-23.1333%2C10000&bias=proximity%3A150.7333%2C-23.1333
yeppoon - nearest hotel: Blossom's on Seaspray
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A122.298%2C29.9576%2C10000&bias=proximity%3A122.298%2C29.9576
shenjiamen - nearest hotel: Zhonghan Hotel
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A10.4518%2C32.9297%2C10000&bias=proximity%3A10.4518%2C32.9297
tataouine - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A167.55%2C-13.8833%2C10000&bias=proximity%3A167.55%2C-13.8833
sola - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-175.2%2C-21.1333%2C10000&bias=proximity%3A-175.2%2C-21.1333
nuku'alofa - nearest hotel: City Hotel
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A43.0333%2C4.55%2C10000&bias=proximity%3A43.0333%2C4.55
yeed - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A80.7911%2C6.024%2C10000&bias=proximity%3A80.7911%2C6.024
tangalle - nearest hotel: Coco Tangalla
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A73.1%2C6.8833%2C10000&bias=proximity%3A73.1%2C6.8833
dhidhdhoo - nearest hotel: Cinnamon Island
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-39.2689%2C-3.2778%2C10000&bias=proximity%3A-39.2689%2C-3.2778
trairi - nearest hotel: Pousada Villa Aurora
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-41.0511%2C-21.6403%2C10000&bias=proximity%3A-41.0511%2C-21.6403
sao joao da barra - nearest hotel: Pousada Mediterrâneo
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A40.902%2C-2.2717%2C10000&bias=proximity%3A40.902%2C-2.2717
lamu - nearest hotel: Hotel Archipelago villa bed and breakfast
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-39.31%2C-8.5142%2C10000&bias=proximity%3A-39.31%2C-8.5142
cabrobo - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A72.642%2C10.5669%2C10000&bias=proximity%3A72.642%2C10.5669
kavaratti - nearest hotel: No hotel found
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A-41.8817%2C-22.7469%2C10000&bias=proximity%3A-41.8817%2C-22.7469
armacao de buzios - nearest hotel: Vila da Santa
https://api.geoapify.com/v2/places?categories=accommodation.hotel&limit=1&apiKey=2746d74c361648528c3ad5d86cbb52c0&filter=circle%3A150.4667%2C-35.35%2C10000&bias=proximity%3A150.4667%2C-35.35
ulladulla - nearest hotel: Hotel Marlin

,City_ID,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date,Hotel Name
0,0,adamstown,-25.0660,-130.1015,21.29,87,100,7.03,PN,1728613084,No hotel found
7,7,mont-dore,-22.2833,166.5833,24.07,62,0,5.80,NC,1728613086,Les Cases de Plum
10,10,port mathurin,-19.6833,63.4167,22.31,79,100,10.56,MU,1728613086,Escale Vacances
60,60,uturoa,-16.7333,-151.4333,23.88,85,100,9.13,PF,1728613099,Hawaiki Nui hotel
69,69,west island,-12.1568,96.8225,26.99,78,20,7.72,CC,1728613101,Cocos Village Bungalows
99,99,bandarbeyla,9.4942,50.8122,25.16,91,64,7.22,SO,1728613109,No hotel found
117,117,afaahiti,-17.7500,-149.2833,21.69,90,100,9.62,PF,1728613113,Omati Lodge
145,145,piacabucu,-10.4056,-36.4344,25.43,69,100,5.38,BR,1728613120,O Leão
150,150,ta`u,-14.2336,-169.5144,26.72,81,51,8.61,AS,1728613121,No hotel found
154,154,nova sintra,14.8667,-24.7167,26.64,85,100,9.93,CV,1728613121,Residência Ka Dencho
157,157,pitimbu,-7.4706,-34.8086,25.02,74,100,5.33,BR,1728613122,Pousada Brisa Mar
186,186,avarua,-21.2078,-159.7750,25.03,73,40,7.72,CK,1728613129,Paradise Inn
206,206,tolanaro,-25.0319,46.9987,21.04,78,20,9.26,MG,1728613134,Hôtel Mahavokey
210,210,forster,-32.1667,152.5167,23.54,69,3,5.06,AU,1728613135,No hotel found
224,224,mahina,-17.5065,-149.4890,24.87,78,75,8.23,PF,1728613138,Motu Martin
265,265,port augusta,-32.5000,137.7667,21.20,26,100,6.68,AU,1728613148,Hotel Commonwealth
278,278,souillac,-20.5167,57.5167,22.21,73,40,6.17,MU,1728613151,Hotel SkylineInn
307,307,yeppoon,-23.1333,150.7333,23.14,72,6,8.80,AU,1728613158,Blossom's on Seaspray
331,331,shenjiamen,29.9576,122.2980,22.23,63,54,5.47,CN,1728613164,Zhonghan Hotel
334,334,tataouine,32.9297,10.4518,23.11,88,10,5.35,TN,1728613164,No hotel found
354,354,sola,-13.8833,167.5500,26.49,80,100,6.77,VU,1728613169,No hotel found
359,359,nuku'alofa,-21.1333,-175.2000,26.19,89,75,6.17,TO,1728613170,City Hotel
409,409,yeed,4.5500,43.0333,23.14,67,22,7.24,SO,1728613181,No hotel found
426,426,tangalle,6.0240,80.7911,25.47,89,100,7.81,LK,1728613185,Coco Tangalla
443,443,dhidhdhoo,6.8833,73.1000,26.15,88,100,9.76,MV,1728613189,Cinnamon Island
470,470,trairi,-3.2778,-39.2689,25.70,74,52,5.71,BR,1728613195,Pousada Villa Aurora
505,505,sao joao da barra,-21.6403,-41.0511,22.36,91,100,7.61,BR,1728613203,Pousada Mediterrâneo
506,506,lamu,-2.2717,40.9020,24.70,84,22,6.59,KE,1728613203,Hotel Archipelago villa bed and breakfast
510,510,cabrobo,-8.5142,-39.3100,25.71,60,20,10.14,BR,1728613204,No hotel found
576,576,kavaratti,10.5669,72.6420,26.39,86,98,7.10,IN,1728613220,No hotel found
585,585,armacao de buzios,-22.7469,-41.8817,21.20,92,100,9.62,BR,1728613223,Vila da Santa
587,587,ulladulla,-35.3500,150.4667,21.18,57,35,6.04,AU,1728613177,Hotel Marlin

### Step 5: Add the hotel name and the country as additional information in the hover message for each city in the map.

In [8]:
%%capture --no-display

# Configure the map plot
hotel_map_plot = hotel_df.hvplot.points(
    "Lng",
    "Lat",
    geo = True,
    tiles = "EsriImagery",
    frame_width = 800,
    frame_height = 600, 
    scale = 0.5,
    color = "City"
)

# Display the map
hotel_map_plot

:Overlay
   .WMTS.I   :WMTS   [Longitude,Latitude]
   .Points.I :Points   [Lng,Lat]   (City)